baseURL = "http://example.org/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "My New Hugo Site"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.tw]
languageName = "繁體中文"
weight = 2


# Author config
[author]
  name = "xxxx"
  email = ""
  link = ""

# Menu config
[menu]
  [[languages.en.menu.main]]
  name = "home"
  url = "/"

  [[languages.en.menu.main]]
  name = "about me"
  url = "/about"

  [[languages.en.menu.main]]
  name = "Posts"
  url = "/posts"

  [[languages.en.menu.main]]
  name = "Tags"
  url = "/tags"

  [[languages.en.menu.main]]
  name = "Categories"
  url = "/categories"

  [[languages.tw.menu.main]]
  name = "主頁"
  url = "/"

  [[languages.tw.menu.main]]
  name = "關於我"
  url = "/about"

  [[languages.tw.menu.main]]
  name = "貼文"
  url = "/posts"

  [[languages.tw.menu.main]]
  name = "標籤"
  url = "/tags"

  [[languages.tw.menu.main]]
  name = "分類"
  url = "/categories"


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false